version: "3"

services:
  app:
    build: ./backend
    image: library-cosmart-project
    container_name: library-cosmart-project
    environment:
      - DB_SERVER=database
      - POSTGRES_DB=library_cosmart
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - private

  database:
    build: ./database
    container_name: database
    ports:
      - "5440:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#      # copy the sql script to create tables
#      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#      # copy the sql script to fill tables
#      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - private

networks:
  private:
    external: false